// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKDBNpg4Jnbnt_gdCiMdD422ga2VzrKF8',
    appId: '1:1015994202499:web:b9cd989f02e584da04deb6',
    messagingSenderId: '1015994202499',
    projectId: 'emart1-9a812',
    authDomain: 'emart1-9a812.firebaseapp.com',
    storageBucket: 'emart1-9a812.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ebJy2VPztqXEZr_qL-m75tE5JNZ0wwI',
    appId: '1:1015994202499:android:2191ab321cd460f504deb6',
    messagingSenderId: '1015994202499',
    projectId: 'emart1-9a812',
    storageBucket: 'emart1-9a812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUzeU3Dx6Kk1_zMEdVFHS5thrUbHBTlU',
    appId: '1:1015994202499:ios:aff8e37fde582d0504deb6',
    messagingSenderId: '1015994202499',
    projectId: 'emart1-9a812',
    storageBucket: 'emart1-9a812.appspot.com',
    iosClientId: '1015994202499-rdfmrknf5e4r5aos1h9kgr0v4i1994qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUzeU3Dx6Kk1_zMEdVFHS5thrUbHBTlU',
    appId: '1:1015994202499:ios:e8126b1f297bacb104deb6',
    messagingSenderId: '1015994202499',
    projectId: 'emart1-9a812',
    storageBucket: 'emart1-9a812.appspot.com',
    iosClientId: '1015994202499-e120e101hbq9anmjmmd7v6r0peatstjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp.RunnerTests',
  );
}
